name: Test
on:
  issues:
    types:
      ['labeled', 'unlabeled']
jobs:
  timer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: ${{ github.event.action == 'unlabeled' && github.event.label.name == '対応中' }}
        uses: actions/checkout@v2
      - name: test_run
        uses: tbsmcd/label_timer@master
        id: test_run
        with:
          targets: '対応中, 依頼中'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: add_time_label
        if: ${{ github.event.action == 'unlabeled' && github.event.label.name == '対応中' }}
        run: |
          pip install requests
          python .github/add_time_label.py ${{ secrets.GITHUB_TOKEN }} ${{ github.event.issue.url }} ${{ steps.test_run.outputs.sum_seconds }}
          
