name: Test
on:
  issues:
    types:
      ['labeled', 'unlabeled']
jobs:
  timer:
    runs-on: ubuntu-latest
    steps:
      - name: test_run
        uses: tbsmcd/label_timer@master
        with:
          targets: '対応中, 依頼中'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: which_jq
        run: |
          which jq
      - name: show_outputs
        run: |
          echo '${{steps.test_run.outputs.LABEL_TIMER_RESULTS}}' | jq
