name: Test
on:
  issues:
    types:
      ['labeled', 'unlabeled']
jobs:
  timer:
    runs-on: ubuntu-latest
    steps:
      - name: test_run
        uses: tbsmcd/label_timer@master
        id: test_run
        with:
          targets: '対応中, 依頼中'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: show_outputs
        run: |
          echo 'Action ${{ steps.test_run.outputs.action }}'
          echo 'Label ${{ steps.test_run.outputs.label }}'
          echo 'Passed seconds ${{ steps.test_run.outputs.passed_seconds }}'
          echo 'Sum seconds ${{ steps.test_run.outputs.sum_seconds }}'
      - name: check_python
        run: |
          which python
          python --version
      - name: checkout
        if: ${{ github.event.action == 'unlabeled' && github.event.label.name == '対応中' }}
        uses: actions/checkout@v2
      - name: add_time_label
        if: ${{ github.event.action == 'unlabeled' && github.event.label.name == '対応中' }}
        run: |
          pip install requests
          echo 'Sum seconds ${{ steps.test_run.outputs.sum_seconds }}'
          python .github/add_time_label.py ${{ secrets.GITHUB_TOKEN }} ${{ steps.test_run.outputs.sum_seconds }}
          
